[project]
name = 'On-Chain-Will-Execution'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.On-Chain-Will-Execution]
path = 'contracts/On-Chain-Will-Execution.clar'
clarity_version = 3
epoch = 3.1

[contracts.Will-Metadata-Feature]
path = 'contracts/Will-Metadata-Feature.clar'
clarity_version = 3
epoch = 3.1

[contracts.Will-Activity-Logger]
path = 'contracts/Will-Activity-Logger.clar'
clarity_version = 3
epoch = 3.1

[contracts.Will-Backup-Recovery]
path = 'contracts/Will-Backup-Recovery.clar'
clarity_version = 3
epoch = 3.1
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
